

pipeline {
  agent any
 
  //tools {nodejs "recent_node"}
 
        stages {  
            stage('Clonning Git') {
                steps {
                    git 'https://github.com/ivan-molina/TFM_CUCUMBER.git'
                }
            }
            
            stage('Install dependencies') {
                steps {
                    bat '''
                        echo '------------Install dependencies--------------'
                        cd testcafe-cucumber-master
                        npm install
                        npm install testcafe
                        npm i gherkin-testcafe cucumber
                        npm install cucumber-html-reporter --save-dev
                    '''
                }
            }

            stage('Execute test') {
                steps {
                    bat '''
                        echo '------------Execute test--------------'
                        cd testcafe-cucumber-master
                        ./node_modules/.bin/cucumber-js.cmd --format json:./reports/report.json    
                    '''
                    //npm run test-chrome
                }
            }

            stage('Generate reports') {
                steps {
                    bat '''
                        echo '------------Publish reports--------------'
                        cd testcafe-cucumber-master
                        node index.js
                    '''
                }
            } 

            stage('Publish HTML Report') {
                steps{
                    publishHTML (target: [
                        allowMissing: false,
                        alwaysLinkToLastBuild: false,
                        keepAll: true,
                        reportDir: 'testcafe-cucumber-master/test/report',
                        reportFiles: 'cucumber_report.html',
                        reportName: "cucumber_report.html"
                    ])
                }
            } 

            stage('Generate CUCUMBER REPORT') {
                steps{
                    cucumber buildStatus: "UNSTABLE",
                    fileIncludePattern: "report.json",
                    jsonReportDirectory: 'testcafe-cucumber-master/reports'
                }
            }

            stage('Slack Message') {
                steps {
                    if ( buildResult == "SUCCESS" ) {
                        slackSend color: "good", message: "Job: ${env.JOB_NAME} with buildnumber ${env.BUILD_NUMBER} was successful"
                    }
                    else if( buildResult == "FAILURE" ) { 
                        slackSend color: "danger", message: "Job: ${env.JOB_NAME} with buildnumber ${env.BUILD_NUMBER} was failed"
                    }
                    else if( buildResult == "UNSTABLE" ) { 
                        slackSend color: "warning", message: "Job: ${env.JOB_NAME} with buildnumber ${env.BUILD_NUMBER} was unstable"
                    }
                    else {
                        slackSend color: "danger", message: "Job: ${env.JOB_NAME} with buildnumber ${env.BUILD_NUMBER} its resulat was unclear"	
                    }

                    //slackSend channel: '#tfm',
                    //    color: 'good',
                    //    message: "*${currentBuild.currentResult}:* Job ${env.JOB_NAME} build ${env.BUILD_NUMBER}\n More info at: ${env.BUILD_URL}"
                }
            }
            
        }

}
