pipeline {
  agent any
 
  //tools {nodejs "recent_node"}
 
  stages {  
    stage('Clonning Git') {
        steps {
            git 'https://github.com/ivan-molina/TFM_CUCUMBER.git'
        }
    }
    
    stage('Install dependencies') {
        steps {
            bat 'echo %PATH%'
            //sh 'npm install testCafe'
        }
        
    }
    
  }
}